# Generated by Django 2.0.7 on 2018-07-14 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180714_0248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_date_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_date_time',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='last_edited_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_date',
            new_name='edited_date',
        ),
    ]
